# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_schoolclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='courses',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='courses',
            field=models.ManyToManyField(to='users.Course'),
        ),
    ]
