# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170126_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
